// <auto-generated />
using System;
using Conductor.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Conductor.Persistence.Migrations
{
    [DbContext(typeof(ConductorDbContext))]
    [Migration("20250912094317_Update")]
    partial class Update
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Conductor.Core.Modules.ResourceTemplate.Domain.ResourceTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.ToTable("ResourceTemplates");
                });

            modelBuilder.Entity("Conductor.Core.Modules.ResourceTemplate.Domain.ResourceTemplate", b =>
                {
                    b.OwnsMany("Conductor.Core.Modules.ResourceTemplate.Domain.ResourceTemplateVersion", "Versions", b1 =>
                        {
                            b1.Property<Guid>("TemplateId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Version")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT")
                                .HasDefaultValueSql("now()");

                            b1.Property<string>("Notes")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("State")
                                .HasColumnType("INTEGER");

                            b1.HasKey("TemplateId", "Version");

                            b1.ToTable("ResourceTemplateVersion");

                            b1.WithOwner()
                                .HasForeignKey("TemplateId");

                            b1.OwnsOne("Conductor.Core.Modules.ResourceTemplate.Domain.ResourceTemplateVersionSource", "Source", b2 =>
                                {
                                    b2.Property<Guid>("ResourceTemplateVersionTemplateId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("ResourceTemplateVersionVersion")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("BaseUrl")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("FolderPath")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Tag")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.HasKey("ResourceTemplateVersionTemplateId", "ResourceTemplateVersionVersion");

                                    b2.ToTable("ResourceTemplateVersion");

                                    b2.WithOwner()
                                        .HasForeignKey("ResourceTemplateVersionTemplateId", "ResourceTemplateVersionVersion");
                                });

                            b1.Navigation("Source")
                                .IsRequired();
                        });

                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
