// <auto-generated />
using System;
using Conductor.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Conductor.Persistence.Migrations
{
    [DbContext(typeof(ConductorDbContext))]
    partial class ConductorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("Conductor.Core.Application.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("Conductor.Core.Deployment.Deployment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CommitId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("EnvironmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("EnvironmentId");

                    b.ToTable("Deployments");
                });

            modelBuilder.Entity("Conductor.Core.Environment.Environment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.ToTable("Environments");
                });

            modelBuilder.Entity("Conductor.Core.ResourceTemplate.ResourceTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ResourceTemplates");
                });

            modelBuilder.Entity("Conductor.Core.Application.Application", b =>
                {
                    b.OwnsOne("Conductor.Core.Application.Repository", "Repository", b1 =>
                        {
                            b1.Property<Guid>("ApplicationId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Provider")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("ApplicationId");

                            b1.ToTable("Applications");

                            b1.WithOwner()
                                .HasForeignKey("ApplicationId");
                        });

                    b.Navigation("Repository")
                        .IsRequired();
                });

            modelBuilder.Entity("Conductor.Core.Deployment.Deployment", b =>
                {
                    b.HasOne("Conductor.Core.Application.Application", null)
                        .WithMany("Deployments")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Conductor.Core.Environment.Environment", null)
                        .WithMany("Deployments")
                        .HasForeignKey("EnvironmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Conductor.Core.ResourceTemplate.ResourceTemplate", b =>
                {
                    b.OwnsMany("Conductor.Core.ResourceTemplate.ResourceTemplateVersion", "Versions", b1 =>
                        {
                            b1.Property<Guid>("TemplateId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Version")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("CreatedAt")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT")
                                .HasDefaultValueSql("now()");

                            b1.Property<string>("Notes")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("State")
                                .HasColumnType("INTEGER");

                            b1.HasKey("TemplateId", "Version");

                            b1.ToTable("ResourceTemplateVersion");

                            b1.WithOwner()
                                .HasForeignKey("TemplateId");

                            b1.OwnsOne("Conductor.Core.ResourceTemplate.ResourceTemplateVersionSource", "Source", b2 =>
                                {
                                    b2.Property<Guid>("ResourceTemplateVersionTemplateId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("ResourceTemplateVersionVersion")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("BaseUrl")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("FolderPath")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Tag")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.HasKey("ResourceTemplateVersionTemplateId", "ResourceTemplateVersionVersion");

                                    b2.ToTable("ResourceTemplateVersion");

                                    b2.WithOwner()
                                        .HasForeignKey("ResourceTemplateVersionTemplateId", "ResourceTemplateVersionVersion");
                                });

                            b1.Navigation("Source")
                                .IsRequired();
                        });

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Conductor.Core.Application.Application", b =>
                {
                    b.Navigation("Deployments");
                });

            modelBuilder.Entity("Conductor.Core.Environment.Environment", b =>
                {
                    b.Navigation("Deployments");
                });
#pragma warning restore 612, 618
        }
    }
}
