name: Web - Build & Validate
permissions:
  contents: read

on:
  push:
    branches:
      - master
    paths:
      - 'Conductor.Web/**'
      - '.github/workflows/build-web.yaml'
  pull_request:
    branches:
      - master
    paths:
      - 'Conductor.Web/**'
      - '.github/workflows/build-web.yaml'

jobs:
  build:
    name: "Web Build and Check"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Conductor.Web
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        id: pnpm-install
        with:
          version: 9
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm build

      - name: Audit Packages
        run: pnpm audit