name: Web - Build & Validate

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  SOLUTION_FILE: Conductor.sln

jobs:
  build:
    name: "Web - Build & Check"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web
    steps:
      - name: Checkout repository
        uses: actions/checkout@